DROP TABLE IF EXISTS places CASCADE;

DROP TABLE IF EXISTS items CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS work_schedule CASCADE;

DROP TABLE IF EXISTS contacts CASCADE;
